### PR TITLE
[Localization] Added Korean translation

### PR DESCRIPTION
**Pull request by BEOBMA**
### Changes
- Added Korean translation for the mod
- Improved text readability with consistent terminology

### Other
- Successfully tested most of the translated elements in the latest version of the mod.

### Contributors
This translation was a collaborative effort. The following contributors worked together on this project:
@BEOBMA
@moviejw

### CODE REVIEW

**Comment by erasels** [comment]
We appreciate it! How should I contact you if changes to cards are made? Should I credit you with your github names?
Also, Packmaster is split into two mods, the core 50 packs and the expansion packs mod, which you can find here
https://github.com/erasels/Packmaster-Expansion-Packs/tree/main/src/main/resources/anniv5Resources/localization
Will you also translate that, or will it only be the core packs? As this is a massive project I understand if you'd rather not also support the expansion packs, however that means I won't be adding the korean language tag to the workshop page, as it wouldn't be a full translation.

**Comment by moviejw** [comment]
I'm working on the expansion pack now. Maybe I can finish it next Monday~Tuesday.

**Comment by moviejw** [comment]
For any changes or new packs, contact snumodder on discord and I'll do it.

**Comment by erasels** [comment]
Great, I'll do that then and thank you again.

Please let me know when this PR is ready to be merged, I'm unsure if it's still actively in development, considering the new commit. Also, just a heads-up, as the new anniversary project is currently in development, updates for the older ones are paused until its release. That means that there won't be another packmaster update until at least 19.01.2025, so you have plenty of time and there is no need to rush the translation of expansion packs :)

**Comment by BEOBMA** [comment]
I have finished reviewing all the packs and cards that can be checked, so it seems this pull request can be merged.

**Comment by erasels** [comment]
Thank you!

**Pull request merged**
